export const productsPart1 = [
    // ==========================
    // SAMSUNG
    // ==========================
    {
        name: "Samsung Galaxy S24 Ultra",
        description: "Experience the pinnacle of Android innovation with the Samsung Galaxy S24 Ultra. Featuring a stunning 6.8-inch Dynamic AMOLED 2X display with a 120Hz refresh rate, this device delivers unparalleled visual clarity. The titanium frame ensures durability while maintaining a premium feel. Powered by the Snapdragon 8 Gen 3 for Galaxy, it handles the most demanding tasks with ease. Capture every moment in breathtaking detail with the 200MP main camera and AI-enhanced zoom capabilities.",
        price: 1299,
        category: "Samsung",
        brand: "Samsung",
        stock: 50,
        rating: 4.9,
        isFeatured: true,
        images: [],
        specs: { "Storage": "512GB", "RAM": "12GB", "Camera": "200MP Main", "Screen": "6.8-inch AMOLED" },
        tags: ["phone", "samsung", "flagship", "android", "ai"]
    },
    {
        name: "Samsung Galaxy S24+",
        description: "The perfect balance of size and power. 6.7-inch QHD+ display and long-lasting battery.",
        price: 999,
        category: "Samsung",
        brand: "Samsung",
        stock: 60,
        rating: 4.8,
        images: [],
        specs: { "Storage": "256GB", "RAM": "12GB", "Screen": "6.7-inch QHD+" },
        tags: ["phone", "samsung", "android"]
    },
    {
        name: "Samsung Galaxy S24",
        description: "Compact design, powerful performance. The essential Galaxy experience.",
        price: 799,
        category: "Samsung",
        brand: "Samsung",
        stock: 80,
        rating: 4.7,
        images: [],
        specs: { "Storage": "128GB", "Screen": "6.2-inch FHD+" },
        tags: ["phone", "samsung", "compact"]
    },
    {
        name: "Samsung Galaxy Z Fold 5",
        description: "Unfold a world of possibilities. Massive 7.6-inch main screen for multitasking.",
        price: 1799,
        category: "Samsung",
        brand: "Samsung",
        stock: 30,
        rating: 4.8,
        images: [],
        specs: { "Storage": "512GB", "Screen": "Foldable 7.6-inch" },
        tags: ["phone", "samsung", "foldable", "premium"]
    },
    {
        name: "Samsung Galaxy Z Flip 5",
        description: "Pocket-sized perfection. Large Flex Window for quick access to apps.",
        price: 999,
        category: "Samsung",
        brand: "Samsung",
        stock: 40,
        rating: 4.7,
        images: [],
        specs: { "Storage": "256GB", "Screen": "Foldable 6.7-inch" },
        tags: ["phone", "samsung", "foldable", "stylish"]
    },
    {
        name: "Samsung Galaxy A55",
        description: "Awesome for everyone. Premium metal frame and vivid Nightography.",
        price: 479,
        category: "Samsung",
        brand: "Samsung",
        stock: 100,
        rating: 4.5,
        images: [],
        specs: { "Storage": "128GB", "Camera": "50MP" },
        tags: ["phone", "samsung", "midrange"]
    },
    {
        name: "Samsung Galaxy Watch 6 Classic",
        description: "The rotating bezel is back. Advanced sleep coaching and heart health monitoring.",
        price: 399,
        category: "Samsung",
        brand: "Samsung",
        stock: 50,
        rating: 4.7,
        images: [],
        specs: { "Size": "47mm", "Health": "BIA Sensor" },
        tags: ["watch", "samsung", "wearable"]
    },
    {
        name: "Samsung Galaxy Buds2 Pro",
        description: "24-bit Hi-Fi audio, Intelligent ANC, and 360 Audio for immersive sound.",
        price: 229,
        category: "Samsung",
        brand: "Samsung",
        stock: 120,
        rating: 4.6,
        images: [],
        specs: { "Audio": "24-bit Hi-Fi", "ANC": "Yes" },
        tags: ["audio", "buds", "samsung"]
    },
    {
        name: "Samsung Galaxy Tab S9 Ultra",
        description: "The new standard for premium tablets. Dynamic AMOLED 2X display and IP68 rating.",
        price: 1199,
        category: "Samsung",
        brand: "Samsung",
        stock: 25,
        rating: 4.9,
        images: [],
        specs: { "Screen": "14.6 inch", "S-Pen": "Included" },
        tags: ["tablet", "samsung", "android"]
    },
    {
        name: "Samsung Galaxy Book 4 Pro",
        description: "Intelligent performance, mobility, and connectivity. AI-ready laptop.",
        price: 1449,
        category: "Samsung",
        brand: "Samsung",
        stock: 20,
        rating: 4.7,
        images: [],
        specs: { "Processor": "Intel Core Ultra 7", "Screen": "14-inch AMOLED" },
        tags: ["laptop", "samsung", "windows"]
    },

    // ==========================
    // APPLE
    // ==========================
    {
        name: "iPhone 15 Pro Max",
        description: "Forged in titanium. A17 Pro chip. The most powerful iPhone ever.",
        price: 1199,
        category: "Apple",
        brand: "Apple",
        stock: 60,
        rating: 4.9,
        isFeatured: true,
        images: [],
        specs: { "Storage": "256GB", "Chip": "A17 Pro", "Camera": "48MP + 5x Zoom" },
        tags: ["phone", "apple", "iphone", "flagship"]
    },
    {
        name: "iPhone 15 Pro",
        description: "Titanium design, A17 Pro chip, and Action button. Pro performance in a compact size.",
        price: 999,
        category: "Apple",
        brand: "Apple",
        stock: 70,
        rating: 4.8,
        images: [],
        specs: { "Storage": "128GB", "Chip": "A17 Pro" },
        tags: ["phone", "apple", "iphone"]
    },
    {
        name: "iPhone 15",
        description: "Dynamic Island, 48MP Main camera, and USB-C. A huge leap forward.",
        price: 799,
        category: "Apple",
        brand: "Apple",
        stock: 100,
        rating: 4.7,
        images: [],
        specs: { "Storage": "128GB", "Chip": "A16 Bionic" },
        tags: ["phone", "apple", "iphone"]
    },
    {
        name: "iPad Pro 12.9 (M2)",
        description: "The ultimate iPad experience. M2 chip and Liquid Retina XDR display.",
        price: 1099,
        category: "Apple",
        brand: "Apple",
        stock: 30,
        rating: 4.9,
        images: [],
        specs: { "Chip": "M2", "Screen": "12.9 inch XDR" },
        tags: ["tablet", "apple", "ipad", "pro"]
    },
    {
        name: "MacBook Pro 16 (M3 Max)",
        description: "Mind-blowing performance. Up to 22 hours of battery life.",
        price: 3499,
        category: "Apple",
        brand: "Apple",
        stock: 15,
        rating: 4.9,
        images: [],
        specs: { "Chip": "M3 Max", "RAM": "36GB", "Storage": "1TB" },
        tags: ["laptop", "apple", "macbook", "pro"]
    },
    {
        name: "MacBook Air 15 (M3)",
        description: "Lean. Mean. M3 machine. The world's best 15-inch consumer laptop.",
        price: 1299,
        category: "Apple",
        brand: "Apple",
        stock: 50,
        rating: 4.8,
        images: [],
        specs: { "Chip": "M3", "Screen": "15.3 inch" },
        tags: ["laptop", "apple", "macbook", "air"]
    },
    {
        name: "Apple Watch Ultra 2",
        description: "Next-level adventure. The brightest Apple display ever.",
        price: 799,
        category: "Apple",
        brand: "Apple",
        stock: 40,
        rating: 4.9,
        images: [],
        specs: { "Case": "Titanium", "Battery": "36 Hours" },
        tags: ["watch", "apple", "wearable"]
    },
    {
        name: "AirPods Pro (2nd Gen)",
        description: "Adaptive Audio, Active Noise Cancellation, and Transparency mode.",
        price: 249,
        category: "Apple",
        brand: "Apple",
        stock: 200,
        rating: 4.8,
        images: [],
        specs: { "Case": "USB-C", "ANC": "Yes" },
        tags: ["audio", "apple", "airpods"]
    },
    {
        name: "Apple Pencil (2nd Gen)",
        description: "Pixel-perfect precision and low latency. Magnetic charging.",
        price: 129,
        category: "Apple",
        brand: "Apple",
        stock: 100,
        rating: 4.7,
        images: [],
        specs: { "Compatibility": "iPad Pro/Air" },
        tags: ["accessory", "apple", "creative"]
    },
    {
        name: "Mac Mini (M2)",
        description: "More muscle. More hustle. Supercharged by M2.",
        price: 599,
        category: "Apple",
        brand: "Apple",
        stock: 40,
        rating: 4.6,
        images: [],
        specs: { "Chip": "M2", "Storage": "256GB" },
        tags: ["desktop", "apple", "mac"]
    },

    // ==========================
    // SMARTPHONES
    // ==========================
    {
        name: "Google Pixel 8 Pro",
        description: "The AI phone built by Google. Best-in-class camera and helpful AI features.",
        price: 999,
        category: "Smartphones",
        brand: "Google",
        stock: 45,
        rating: 4.7,
        images: [],
        specs: { "Chip": "Tensor G3", "Camera": "50MP" },
        tags: ["phone", "google", "pixel", "android"]
    },
    {
        name: "OnePlus 12",
        description: "Smooth beyond belief. Snapdragon 8 Gen 3 and massive battery.",
        price: 799,
        category: "Smartphones",
        brand: "OnePlus",
        stock: 50,
        rating: 4.8,
        images: [],
        specs: { "Chip": "Snapdragon 8 Gen 3", "Charging": "100W" },
        tags: ["phone", "oneplus", "android"]
    },
    {
        name: "Xiaomi 14 Ultra",
        description: "Leica optics. A lens to legend. The ultimate photography smartphone.",
        price: 1299,
        category: "Smartphones",
        brand: "Xiaomi",
        stock: 30,
        rating: 4.8,
        images: [],
        specs: { "Camera": "Quad 50MP Leica", "Chip": "Snapdragon 8 Gen 3" },
        tags: ["phone", "xiaomi", "camera", "android"]
    },
    {
        name: "Nothing Phone (2)",
        description: "Come to the bright side. Iconic Glyph Interface and Nothing OS.",
        price: 699,
        category: "Smartphones",
        brand: "Nothing",
        stock: 40,
        rating: 4.6,
        images: [],
        specs: { "Interface": "Glyph", "Screen": "LTPO OLED" },
        tags: ["phone", "nothing", "unique", "android"]
    },
    {
        name: "Tecno Camon 30 Premier",
        description: "Portrait Master. 50MP Sony IMX890 sensor for stunning shots.",
        price: 450,
        category: "Smartphones",
        brand: "Tecno",
        stock: 80,
        rating: 4.5,
        images: [],
        specs: { "Camera": "50MP", "Charging": "70W" },
        tags: ["phone", "tecno", "android"]
    },
    {
        name: "Infinix Note 40 Pro",
        description: "Take charge. 100W FastCharge and 3D Curved AMOLED.",
        price: 350,
        category: "Smartphones",
        brand: "Infinix",
        stock: 100,
        rating: 4.4,
        images: [],
        specs: { "Charging": "100W", "Screen": "120Hz" },
        tags: ["phone", "infinix", "android"]
    },
    {
        name: "Sony Xperia 1 V",
        description: "Next-gen sensor. Next-gen imaging. For creators.",
        price: 1399,
        category: "Smartphones",
        brand: "Sony",
        stock: 20,
        rating: 4.7,
        images: [],
        specs: { "Screen": "4K OLED", "Audio": "3.5mm Jack" },
        tags: ["phone", "sony", "creator", "android"]
    },
    {
        name: "Google Pixel 7a",
        description: "Built to perform. Priced to play. The best value Pixel.",
        price: 499,
        category: "Smartphones",
        brand: "Google",
        stock: 90,
        rating: 4.6,
        images: [],
        specs: { "Chip": "Tensor G2", "Camera": "64MP" },
        tags: ["phone", "google", "value", "android"]
    },
    {
        name: "OnePlus Open",
        description: "Open for everything. The best foldable experience.",
        price: 1699,
        category: "Smartphones",
        brand: "OnePlus",
        stock: 15,
        rating: 4.9,
        images: [],
        specs: { "Screen": "Foldable", "RAM": "16GB" },
        tags: ["phone", "oneplus", "foldable", "android"]
    },
    {
        name: "Motorola Razr+",
        description: "Flip the script. The largest external display on a flip phone.",
        price: 999,
        category: "Smartphones",
        brand: "Motorola",
        stock: 30,
        rating: 4.5,
        images: [],
        specs: { "Screen": "Foldable", "Refresh": "165Hz" },
        tags: ["phone", "motorola", "foldable", "android"]
    },

    // ==========================
    // LAPTOPS
    // ==========================
    {
        name: "Dell XPS 15",
        description: "Immersive display. Powerful performance. The creator's choice.",
        price: 1899,
        category: "Laptops",
        brand: "Dell",
        stock: 30,
        rating: 4.7,
        images: [],
        specs: { "Processor": "i9", "GPU": "RTX 4060", "Screen": "OLED" },
        tags: ["laptop", "dell", "windows", "creator"]
    },
    {
        name: "HP Spectre x360",
        description: "Craftsmanship meets power. 2-in-1 convertible design.",
        price: 1599,
        category: "Laptops",
        brand: "HP",
        stock: 25,
        rating: 4.6,
        images: [],
        specs: { "Type": "2-in-1", "Screen": "Touch OLED" },
        tags: ["laptop", "hp", "convertible"]
    },
    {
        name: "Lenovo ThinkPad X1 Carbon",
        description: "Ultralight. Ultrathin. The gold standard for business laptops.",
        price: 1799,
        category: "Laptops",
        brand: "Lenovo",
        stock: 40,
        rating: 4.8,
        images: [],
        specs: { "Weight": "1.12kg", "Durability": "Mil-Spec" },
        tags: ["laptop", "lenovo", "business"]
    },
    {
        name: "ASUS ROG Zephyrus G14",
        description: "The world's most powerful 14-inch gaming laptop.",
        price: 1599,
        category: "Laptops",
        brand: "ASUS",
        stock: 35,
        rating: 4.8,
        images: [],
        specs: { "GPU": "RTX 4070", "Screen": "120Hz OLED" },
        tags: ["laptop", "gaming", "asus"]
    },
    {
        name: "Razer Blade 16",
        description: "Bigger. Better. Still the best. Desktop performance in a laptop.",
        price: 2999,
        category: "Laptops",
        brand: "Razer",
        stock: 10,
        rating: 4.9,
        images: [],
        specs: { "GPU": "RTX 4090", "Screen": "Dual Mode Mini-LED" },
        tags: ["laptop", "gaming", "razer", "premium"]
    },
    {
        name: "Microsoft Surface Laptop 5",
        description: "Blazing fast, sophisticated style. Touchscreen PixelSense display.",
        price: 1299,
        category: "Laptops",
        brand: "Microsoft",
        stock: 45,
        rating: 4.5,
        images: [],
        specs: { "Screen": "13.5 inch Touch", "Finish": "Alcantara" },
        tags: ["laptop", "microsoft", "surface"]
    },
    {
        name: "Acer Swift Go 14",
        description: "Ready to go. AI-ready performance in a thin and light body.",
        price: 899,
        category: "Laptops",
        brand: "Acer",
        stock: 60,
        rating: 4.4,
        images: [],
        specs: { "Processor": "Core Ultra 5", "Weight": "1.3kg" },
        tags: ["laptop", "acer", "budget"]
    },
    {
        name: "MSI Raider GE78",
        description: "Light 'em up. The ultimate RGB gaming powerhouse.",
        price: 2499,
        category: "Laptops",
        brand: "MSI",
        stock: 15,
        rating: 4.7,
        images: [],
        specs: { "GPU": "RTX 4080", "RGB": "Matrix Bar" },
        tags: ["laptop", "gaming", "msi"]
    },
    {
        name: "LG Gram 17",
        description: "Impossibly light. Unbelievably powerful. 17-inch screen, under 3 lbs.",
        price: 1699,
        category: "Laptops",
        brand: "LG",
        stock: 20,
        rating: 4.6,
        images: [],
        specs: { "Weight": "1.35kg", "Battery": "20 Hours" },
        tags: ["laptop", "lg", "lightweight"]
    },
    {
        name: "Framework Laptop 13",
        description: "The laptop you can upgrade, repair, and customize.",
        price: 1099,
        category: "Laptops",
        brand: "Framework",
        stock: 25,
        rating: 4.8,
        images: [],
        specs: { "Modular": "Yes", "Repairable": "10/10" },
        tags: ["laptop", "framework", "sustainable"]
    },

    // ==========================
    // ACCESSORIES
    // ==========================
    {
        name: "Logitech MX Master 3S",
        description: "An icon remastered. Quiet clicks and 8K DPI tracking.",
        price: 99,
        category: "Accessories",
        brand: "Logitech",
        stock: 150,
        rating: 4.9,
        images: [],
        specs: { "DPI": "8000", "Connectivity": "Bluetooth/Bolt" },
        tags: ["accessory", "mouse", "productivity"]
    },
    {
        name: "Keychron K2 Pro",
        description: "Wireless mechanical keyboard. QMK/VIA support for endless customization.",
        price: 119,
        category: "Accessories",
        brand: "Keychron",
        stock: 80,
        rating: 4.8,
        images: [],
        specs: { "Switch": "Red/Blue/Brown", "Layout": "75%" },
        tags: ["accessory", "keyboard", "mechanical"]
    },
    {
        name: "Anker 737 Power Bank",
        description: "Ultra-powerful two-way charging. 24,000mAh capacity.",
        price: 149,
        category: "Accessories",
        brand: "Anker",
        stock: 100,
        rating: 4.9,
        images: [],
        specs: { "Capacity": "24000mAh", "Output": "140W" },
        tags: ["accessory", "powerbank", "charging"]
    },
    {
        name: "Samsung T7 Shield 2TB",
        description: "Rugged durability. Fast speeds. IP65 water/dust resistance.",
        price: 179,
        category: "Accessories",
        brand: "Samsung",
        stock: 60,
        rating: 4.8,
        images: [],
        specs: { "Speed": "1050MB/s", "Rugged": "Yes" },
        tags: ["accessory", "storage", "ssd"]
    },
    {
        name: "Belkin 3-in-1 Wireless Charger",
        description: "Fast wireless charging for iPhone, Apple Watch, and AirPods.",
        price: 149,
        category: "Accessories",
        brand: "Belkin",
        stock: 70,
        rating: 4.7,
        images: [],
        specs: { "MagSafe": "Yes", "Power": "15W" },
        tags: ["accessory", "charger", "wireless"]
    },
    {
        name: "Satechi USB-C Multiport Adapter",
        description: "Expansion made easy. 4K HDMI, USB-C PD, and more.",
        price: 79,
        category: "Accessories",
        brand: "Satechi",
        stock: 90,
        rating: 4.6,
        images: [],
        specs: { "Ports": "V2", "HDMI": "4K" },
        tags: ["accessory", "hub", "dongle"]
    },
    {
        name: "Peak Design Tech Pouch",
        description: "Unrivaled organization. Origami-style pockets for all your gear.",
        price: 59,
        category: "Accessories",
        brand: "Peak Design",
        stock: 50,
        rating: 4.9,
        images: [],
        specs: { "Material": "Recycled Nylon", "Weatherproof": "Yes" },
        tags: ["accessory", "bag", "organizer"]
    },
    {
        name: "Apple Magic Trackpad",
        description: "Wireless and rechargeable. The full range of Multi-Touch gestures.",
        price: 129,
        category: "Accessories",
        brand: "Apple",
        stock: 40,
        rating: 4.8,
        images: [],
        specs: { "Color": "Black/White", "Connection": "Bluetooth" },
        tags: ["accessory", "apple", "input"]
    },
    {
        name: "Logitech C920x Webcam",
        description: "Full HD 1080p video calling and recording. The standard for webcams.",
        price: 69,
        category: "Accessories",
        brand: "Logitech",
        stock: 100,
        rating: 4.7,
        images: [],
        specs: { "Resolution": "1080p", "Mic": "Stereo" },
        tags: ["accessory", "webcam", "streaming"]
    },
    {
        name: "Elgato Stream Deck MK.2",
        description: "15 LCD keys to control your apps and tools. Fully customizable.",
        price: 149,
        category: "Accessories",
        brand: "Elgato",
        stock: 60,
        rating: 4.9,
        images: [],
        specs: { "Keys": "15", "Interface": "USB" },
        tags: ["accessory", "streaming", "productivity"]
    }
];
