export const productsPart2 = [
    // ==========================
    // MOBILE ACCESSORIES
    // ==========================
    {
        name: "Casetify Impact Case",
        description: "Strong protection. Fun designs. Military-grade drop tested.",
        price: 65,
        category: "Mobile Accessories",
        brand: "Casetify",
        stock: 200,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800"],
        specs: { "Drop Protection": "6.6ft", "Material": "EcoShock" },
        tags: ["accessory", "case", "phone"]
    },
    {
        name: "Spigen Ultra Hybrid",
        description: "Crystal clear transparency. Hybrid technology for optimal protection.",
        price: 30,
        category: "Mobile Accessories",
        brand: "Spigen",
        stock: 300,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&q=80&w=800"],
        specs: { "Material": "TPU + PC", "Clarity": "Long-lasting" },
        tags: ["accessory", "case", "value"]
    },
    {
        name: "Anker Nano II 65W",
        description: "Charge phones, tablets, and notebooks at high speed. Compact design.",
        price: 49,
        category: "Mobile Accessories",
        brand: "Anker",
        stock: 150,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800"],
        specs: { "Power": "65W", "Tech": "GaN II" },
        tags: ["accessory", "charger", "fast"]
    },
    {
        name: "Apple MagSafe Battery Pack",
        description: "Snap on for extra battery life. Compact and intuitive.",
        price: 99,
        category: "Mobile Accessories",
        brand: "Apple",
        stock: 80,
        rating: 4.5,
        images: ["https://images.unsplash.com/photo-1622445272461-c6580cab8755?auto=format&fit=crop&q=80&w=800"],
        specs: { "Capacity": "1460mAh", "Type": "Magnetic" },
        tags: ["accessory", "powerbank", "apple"]
    },
    {
        name: "PopSockets MagSafe Grip",
        description: "Magnetic phone grip and stand. Swappable top.",
        price: 29,
        category: "Mobile Accessories",
        brand: "PopSockets",
        stock: 250,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800"],
        specs: { "Mount": "MagSafe", "Function": "Grip/Stand" },
        tags: ["accessory", "grip", "phone"]
    },
    {
        name: "Nomad Modern Leather Case",
        description: "Horween leather from the USA. Develops a rugged patina.",
        price: 50,
        category: "Mobile Accessories",
        brand: "Nomad",
        stock: 60,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&q=80&w=800"],
        specs: { "Material": "Leather", "MagSafe": "Yes" },
        tags: ["accessory", "case", "premium"]
    },
    {
        name: "Anker 622 Magnetic Battery",
        description: "Snap. Charge. Chill. Built-in foldable kickstand.",
        price: 59,
        category: "Mobile Accessories",
        brand: "Anker",
        stock: 100,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1622445272461-c6580cab8755?auto=format&fit=crop&q=80&w=800"],
        specs: { "Capacity": "5000mAh", "Stand": "Yes" },
        tags: ["accessory", "powerbank", "maggo"]
    },
    {
        name: "Samsung 45W Power Adapter",
        description: "Super Fast Charging 2.0. Get back to 100% faster.",
        price: 49,
        category: "Mobile Accessories",
        brand: "Samsung",
        stock: 120,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=800"],
        specs: { "Power": "45W", "Port": "USB-C" },
        tags: ["accessory", "charger", "samsung"]
    },
    {
        name: "DJI Osmo Mobile 6",
        description: "Unfold your creativity. Intelligent smartphone stabilizer.",
        price: 149,
        category: "Mobile Accessories",
        brand: "DJI",
        stock: 40,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1618418386376-745674395e38?auto=format&fit=crop&q=80&w=800"],
        specs: { "Axis": "3-Axis", "Feature": "ActiveTrack 6.0" },
        tags: ["accessory", "gimbal", "video"]
    },
    {
        name: "RhinoShield SolidSuit",
        description: "Tough yet flexible. Premium finish with superior drop protection.",
        price: 35,
        category: "Mobile Accessories",
        brand: "RhinoShield",
        stock: 150,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&q=80&w=800"],
        specs: { "Material": "ShockSpread", "Customizable": "Yes" },
        tags: ["accessory", "case", "durable"]
    },

    // ==========================
    // AUDIO
    // ==========================
    {
        name: "Sony WH-1000XM5",
        description: "Distraction-free listening. Industry-leading noise cancellation.",
        price: 399,
        category: "Audio",
        brand: "Sony",
        stock: 80,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800"],
        specs: { "ANC": "Yes", "Battery": "30 Hours" },
        tags: ["audio", "headphones", "sony"]
    },
    {
        name: "Bose QuietComfort Ultra",
        description: "World-class noise cancellation. Breakthrough spatial audio.",
        price: 429,
        category: "Audio",
        brand: "Bose",
        stock: 60,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&q=80&w=800"],
        specs: { "Audio": "Spatial", "Comfort": "Premium" },
        tags: ["audio", "headphones", "bose"]
    },
    {
        name: "Sennheiser Momentum 4",
        description: "Signature sound. Exceptional comfort. 60-hour battery life.",
        price: 349,
        category: "Audio",
        brand: "Sennheiser",
        stock: 50,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800"],
        specs: { "Battery": "60 Hours", "Sound": "Audiophile" },
        tags: ["audio", "headphones", "sennheiser"]
    },
    {
        name: "JBL Flip 6",
        description: "Bold sound for every adventure. Waterproof and dustproof.",
        price: 129,
        category: "Audio",
        brand: "JBL",
        stock: 150,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800"],
        specs: { "Waterproof": "IP67", "Battery": "12 Hours" },
        tags: ["audio", "speaker", "jbl"]
    },
    {
        name: "Sonos Era 100",
        description: "Next-gen acoustics. New look. Now with Bluetooth.",
        price: 249,
        category: "Audio",
        brand: "Sonos",
        stock: 40,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800"],
        specs: { "Connectivity": "WiFi/BT", "Voice": "Alexa/Sonos" },
        tags: ["audio", "speaker", "home"]
    },
    {
        name: "Marshall Emberton II",
        description: "Rich, clear and loud. 30+ hours of portable playtime.",
        price: 169,
        category: "Audio",
        brand: "Marshall",
        stock: 70,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800"],
        specs: { "Style": "Retro", "Battery": "30+ Hours" },
        tags: ["audio", "speaker", "stylish"]
    },
    {
        name: "Sony WF-1000XM5",
        description: "The best noise cancelling earbuds. Astonishing sound quality.",
        price: 299,
        category: "Audio",
        brand: "Sony",
        stock: 90,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800"],
        specs: { "ANC": "Best-in-class", "Size": "Compact" },
        tags: ["audio", "earbuds", "sony"]
    },
    {
        name: "Nothing Ear (2)",
        description: "Mighty little things. Hi-Res Audio Certified.",
        price: 149,
        category: "Audio",
        brand: "Nothing",
        stock: 60,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800"],
        specs: { "Design": "Transparent", "Codec": "LHDC 5.0" },
        tags: ["audio", "earbuds", "unique"]
    },
    {
        name: "Bose Smart Soundbar 900",
        description: "Immersive sound for all your content. Supports Dolby Atmos.",
        price: 899,
        category: "Audio",
        brand: "Bose",
        stock: 20,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800"],
        specs: { "Audio": "Dolby Atmos", "Voice": "Alexa/Google" },
        tags: ["audio", "soundbar", "home-theater"]
    },
    {
        name: "Blue Yeti X",
        description: "Professional USB microphone for gaming, streaming and podcasting.",
        price: 169,
        category: "Audio",
        brand: "Logitech",
        stock: 40,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800"],
        specs: { "Pattern": "4-Capsule", "Metering": "LED" },
        tags: ["audio", "microphone", "streaming"]
    },

    // ==========================
    // GAMING
    // ==========================
    {
        name: "PlayStation 5 Slim",
        description: "Play Has No Limits. Lightning fast loading and incredible immersion.",
        price: 499,
        category: "Gaming",
        brand: "Sony",
        stock: 100,
        rating: 4.9,
        isFeatured: true,
        images: ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&q=80&w=800"],
        specs: { "Storage": "1TB SSD", "Output": "4K 120Hz" },
        tags: ["gaming", "console", "ps5"]
    },
    {
        name: "Xbox Series X",
        description: "Power your dreams. The fastest, most powerful Xbox ever.",
        price: 499,
        category: "Gaming",
        brand: "Microsoft",
        stock: 80,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&q=80&w=800"],
        specs: { "Performance": "12 TFLOPS", "Storage": "1TB SSD" },
        tags: ["gaming", "console", "xbox"]
    },
    {
        name: "Nintendo Switch OLED",
        description: "7-inch OLED screen. Vivid colors. Crisp contrast.",
        price: 349,
        category: "Gaming",
        brand: "Nintendo",
        stock: 120,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&q=80&w=800"],
        specs: { "Screen": "7-inch OLED", "Mode": "Handheld/TV" },
        tags: ["gaming", "console", "nintendo"]
    },
    {
        name: "Steam Deck OLED",
        description: "Portability meets power. The ultimate handheld PC gaming experience.",
        price: 549,
        category: "Gaming",
        brand: "Valve",
        stock: 40,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1697636637380-6e42258d44c8?auto=format&fit=crop&q=80&w=800"],
        specs: { "Screen": "HDR OLED", "Battery": "Longer Life" },
        tags: ["gaming", "handheld", "pc"]
    },
    {
        name: "ASUS ROG Ally",
        description: "Play All Your Games. Windows 11 handheld gaming.",
        price: 699,
        category: "Gaming",
        brand: "ASUS",
        stock: 50,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1697636637380-6e42258d44c8?auto=format&fit=crop&q=80&w=800"],
        specs: { "Chip": "Ryzen Z1 Extreme", "Screen": "120Hz" },
        tags: ["gaming", "handheld", "windows"]
    },
    {
        name: "DualSense Edge Controller",
        description: "Built for high performance. Customizable controls and profiles.",
        price: 199,
        category: "Gaming",
        brand: "Sony",
        stock: 60,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1592840496011-8b5209bdb0c5?auto=format&fit=crop&q=80&w=800"],
        specs: { "Customizable": "Yes", "Paddles": "Back Buttons" },
        tags: ["gaming", "controller", "pro"]
    },
    {
        name: "Xbox Elite Series 2",
        description: "Adjustable-tension thumbsticks. Wrap-around rubberized grip.",
        price: 179,
        category: "Gaming",
        brand: "Microsoft",
        stock: 50,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1600080972464-8e5f35f63d88?auto=format&fit=crop&q=80&w=800"],
        specs: { "Battery": "40 Hours", "Customizable": "Yes" },
        tags: ["gaming", "controller", "pro"]
    },
    {
        name: "SteelSeries Arctis Nova Pro",
        description: "Almighty Audio. Active Noise Cancellation for gaming.",
        price: 349,
        category: "Gaming",
        brand: "SteelSeries",
        stock: 40,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800"],
        specs: { "Audio": "Hi-Res", "System": "Multi-System" },
        tags: ["gaming", "headset", "wireless"]
    },
    {
        name: "Logitech G Pro X Superlight 2",
        description: "The new weapon of choice for the world's top esports athletes.",
        price: 159,
        category: "Gaming",
        brand: "Logitech",
        stock: 80,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800"],
        specs: { "Weight": "60g", "Sensor": "HERO 2" },
        tags: ["gaming", "mouse", "esports"]
    },
    {
        name: "Razer BlackShark V2 Pro",
        description: "The definitive esports gaming headset. HyperSpeed Wireless.",
        price: 199,
        category: "Gaming",
        brand: "Razer",
        stock: 60,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800"],
        specs: { "Mic": "Super Wideband", "Audio": "THX" },
        tags: ["gaming", "headset", "razer"]
    },

    // ==========================
    // STORAGE
    // ==========================
    {
        name: "Samsung 990 Pro 2TB",
        description: "The ultimate SSD. Blazing fast speeds for gaming and video editing.",
        price: 179,
        category: "Storage",
        brand: "Samsung",
        stock: 100,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "7450MB/s", "Interface": "PCIe 4.0" },
        tags: ["storage", "ssd", "nvme"]
    },
    {
        name: "WD_BLACK SN850X 2TB",
        description: "Crush load times. Top-tier performance for gaming.",
        price: 169,
        category: "Storage",
        brand: "Western Digital",
        stock: 80,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "7300MB/s", "Heatsink": "Optional" },
        tags: ["storage", "ssd", "gaming"]
    },
    {
        name: "SanDisk Extreme Pro 128GB",
        description: "Our most powerful SD UHS-I memory card yet.",
        price: 45,
        category: "Storage",
        brand: "SanDisk",
        stock: 200,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "200MB/s", "Class": "V30" },
        tags: ["storage", "sdcard", "camera"]
    },
    {
        name: "Samsung T9 Portable SSD 1TB",
        description: "Non-stop speed. Rugged durability. USB 3.2 Gen 2x2.",
        price: 139,
        category: "Storage",
        brand: "Samsung",
        stock: 60,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "2000MB/s", "Portable": "Yes" },
        tags: ["storage", "ssd", "external"]
    },
    {
        name: "Seagate IronWolf 8TB",
        description: "Tough. Ready. Scalable. Built for NAS environments.",
        price: 189,
        category: "Storage",
        brand: "Seagate",
        stock: 40,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1531492244965-8969981594b5?auto=format&fit=crop&q=80&w=800"],
        specs: { "RPM": "7200", "Cache": "256MB" },
        tags: ["storage", "hdd", "nas"]
    },
    {
        name: "WD Elements 14TB",
        description: "High-capacity storage. Plug-and-play simplicity.",
        price: 249,
        category: "Storage",
        brand: "Western Digital",
        stock: 30,
        rating: 4.5,
        images: ["https://images.unsplash.com/photo-1531492244965-8969981594b5?auto=format&fit=crop&q=80&w=800"],
        specs: { "Type": "External HDD", "Power": "AC Adapter" },
        tags: ["storage", "hdd", "backup"]
    },
    {
        name: "Kingston XS2000 1TB",
        description: "Pocket-sized portability. High-speed performance.",
        price: 99,
        category: "Storage",
        brand: "Kingston",
        stock: 50,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "2000MB/s", "Size": "Tiny" },
        tags: ["storage", "ssd", "portable"]
    },
    {
        name: "Lexar Professional CFexpress",
        description: "Blazing-fast performance for cinema-quality video.",
        price: 199,
        category: "Storage",
        brand: "Lexar",
        stock: 20,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Type": "Type B", "Speed": "1750MB/s" },
        tags: ["storage", "card", "pro"]
    },
    {
        name: "Samsung PRO Plus microSD 512GB",
        description: "Your new go-to card. Fast read/write speeds.",
        price: 49,
        category: "Storage",
        brand: "Samsung",
        stock: 150,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Class": "A2", "Adapter": "Included" },
        tags: ["storage", "microsd", "android"]
    },
    {
        name: "Crucial X9 Pro 2TB",
        description: "Powerful performance. Professional quality. Portable design.",
        price: 129,
        category: "Storage",
        brand: "Crucial",
        stock: 60,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "1050MB/s", "Durability": "IP55" },
        tags: ["storage", "ssd", "portable"]
    },

    // ==========================
    // TABLETS
    // ==========================
    {
        name: "Samsung Galaxy Tab S9+",
        description: "Crystal clear viewing. Water and dust resistant. S Pen included.",
        price: 999,
        category: "Tablets",
        brand: "Samsung",
        stock: 40,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Screen": "12.4 inch", "Processor": "Snapdragon 8 Gen 2" },
        tags: ["tablet", "samsung", "android"]
    },
    {
        name: "iPad Air (M1)",
        description: "Light. Bright. Full of might. Supercharged by Apple M1.",
        price: 599,
        category: "Tablets",
        brand: "Apple",
        stock: 60,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800"],
        specs: { "Chip": "M1", "Screen": "10.9 inch" },
        tags: ["tablet", "apple", "ipad"]
    },
    {
        name: "iPad mini 6",
        description: "Mega power. Mini sized. All-screen design.",
        price: 499,
        category: "Tablets",
        brand: "Apple",
        stock: 50,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800"],
        specs: { "Chip": "A15 Bionic", "Screen": "8.3 inch" },
        tags: ["tablet", "apple", "compact"]
    },
    {
        name: "Microsoft Surface Pro 9",
        description: "Laptop power, tablet flexibility. 13-inch touchscreen.",
        price: 999,
        category: "Tablets",
        brand: "Microsoft",
        stock: 35,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800"],
        specs: { "OS": "Windows 11", "Kickstand": "Built-in" },
        tags: ["tablet", "windows", "productivity"]
    },
    {
        name: "Lenovo Tab P12",
        description: "Your personal entertainment center. 3K display.",
        price: 349,
        category: "Tablets",
        brand: "Lenovo",
        stock: 50,
        rating: 4.5,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Screen": "12.7 inch", "Speakers": "JBL" },
        tags: ["tablet", "lenovo", "android"]
    },
    {
        name: "Amazon Fire Max 11",
        description: "Our biggest, most powerful tablet yet. Vivid 11-inch screen.",
        price: 229,
        category: "Tablets",
        brand: "Amazon",
        stock: 80,
        rating: 4.4,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Screen": "11 inch", "Body": "Aluminum" },
        tags: ["tablet", "amazon", "budget"]
    },
    {
        name: "Xiaomi Pad 6",
        description: "Productivity ahead. 144Hz WQHD+ eye care display.",
        price: 399,
        category: "Tablets",
        brand: "Xiaomi",
        stock: 60,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Chip": "Snapdragon 870", "Charging": "33W" },
        tags: ["tablet", "xiaomi", "android"]
    },
    {
        name: "OnePlus Pad",
        description: "Smooth without equal. 7:5 ReadFit Display.",
        price: 479,
        category: "Tablets",
        brand: "OnePlus",
        stock: 30,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Refresh": "144Hz", "Battery": "1 Month Standby" },
        tags: ["tablet", "oneplus", "android"]
    },
    {
        name: "Google Pixel Tablet",
        description: "Helpful in your hand. Helpful at home. Charging Speaker Dock included.",
        price: 499,
        category: "Tablets",
        brand: "Google",
        stock: 40,
        rating: 4.5,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Chip": "Tensor G2", "Dock": "Included" },
        tags: ["tablet", "google", "smart-home"]
    },
    {
        name: "Modio M22 Kids Tablet",
        description: "Safe fun for kids. Pre-installed educational apps.",
        price: 89,
        category: "Tablets",
        brand: "Modio",
        stock: 100,
        rating: 4.2,
        images: ["https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&q=80&w=800"],
        specs: { "Screen": "7 inch", "Case": "Rugged" },
        tags: ["tablet", "kids", "budget"]
    },

    // ==========================
    // CONTENT CREATOR KIT
    // ==========================
    {
        name: "DJI Mini 4 Pro",
        description: "Go big with Mini. 4K/60fps HDR video.",
        price: 759,
        category: "Content Creator Kit",
        brand: "DJI",
        stock: 30,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&q=80&w=800"],
        specs: { "Weight": "<249g", "Obstacle Sensing": "Omni" },
        tags: ["creator", "drone", "dji"]
    },
    {
        name: "GoPro HERO12 Black",
        description: "Incredible image quality. HyperSmooth 6.0 stabilization.",
        price: 399,
        category: "Content Creator Kit",
        brand: "GoPro",
        stock: 50,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1564466021188-1e17010c5411?auto=format&fit=crop&q=80&w=800"],
        specs: { "Video": "5.3K", "Waterproof": "33ft" },
        tags: ["creator", "camera", "action"]
    },
    {
        name: "Insta360 X3",
        description: "Magic in action. 5.7K 360-degree capture.",
        price: 449,
        category: "Content Creator Kit",
        brand: "Insta360",
        stock: 40,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1564466021188-1e17010c5411?auto=format&fit=crop&q=80&w=800"],
        specs: { "Video": "360", "Reframing": "AI" },
        tags: ["creator", "camera", "360"]
    },
    {
        name: "DJI Osmo Pocket 3",
        description: "For moving moments. 1-inch CMOS sensor and 4K/120fps.",
        price: 519,
        category: "Content Creator Kit",
        brand: "DJI",
        stock: 25,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1618418386376-745674395e38?auto=format&fit=crop&q=80&w=800"],
        specs: { "Sensor": "1-inch", "Stabilization": "3-Axis" },
        tags: ["creator", "camera", "vlog"]
    },
    {
        name: "Sony ZV-E10",
        description: "Interchangeable-lens vlog camera. Large APS-C sensor.",
        price: 699,
        category: "Content Creator Kit",
        brand: "Sony",
        stock: 20,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800"],
        specs: { "Sensor": "APS-C", "Focus": "Real-time Eye AF" },
        tags: ["creator", "camera", "vlog"]
    },
    {
        name: "Rode Wireless Pro",
        description: "The ultimate wireless microphone system. 32-bit float recording.",
        price: 399,
        category: "Content Creator Kit",
        brand: "Rode",
        stock: 30,
        rating: 4.9,
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800"],
        specs: { "Range": "260m", "Recording": "Onboard" },
        tags: ["creator", "audio", "mic"]
    },
    {
        name: "Neewer Ring Light Kit",
        description: "Professional lighting for streaming and makeup.",
        price: 89,
        category: "Content Creator Kit",
        brand: "Neewer",
        stock: 60,
        rating: 4.5,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800"],
        specs: { "Size": "18 inch", "Stand": "Included" },
        tags: ["creator", "lighting", "studio"]
    },
    {
        name: "Elgato Key Light Air",
        description: "Professional Wi-Fi enabled lighting panel.",
        price: 129,
        category: "Content Creator Kit",
        brand: "Elgato",
        stock: 40,
        rating: 4.7,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800"],
        specs: { "Control": "App", "Temp": "Adjustable" },
        tags: ["creator", "lighting", "streaming"]
    },
    {
        name: "Joby GorillaPod 3K",
        description: "Flexible tripod for cameras up to 3kg.",
        price: 49,
        category: "Content Creator Kit",
        brand: "Joby",
        stock: 100,
        rating: 4.6,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800"],
        specs: { "Legs": "Flexible", "Head": "Ballhead" },
        tags: ["creator", "tripod", "flexible"]
    },
    {
        name: "SanDisk Extreme Portable SSD 1TB",
        description: "Fast storage for editing on the go.",
        price: 99,
        category: "Content Creator Kit",
        brand: "SanDisk",
        stock: 80,
        rating: 4.8,
        images: ["https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&q=80&w=800"],
        specs: { "Speed": "1050MB/s", "Rugged": "Yes" },
        tags: ["creator", "storage", "ssd"]
    }
];
